import {
  ABI_VERSION_MAJOR,
  ABI_VERSION_MINOR,
  ABI_VERSION,
  MEMORY_DESCRIPTOR_SIZE,
  MEMORY_DESCRIPTOR_OFFSET_REGION,
  MEMORY_DESCRIPTOR_OFFSET_OFFSET,
  MEMORY_DESCRIPTOR_OFFSET_LENGTH,
  MEMORY_DESCRIPTOR_OFFSET_CAPACITY,
  MEMORY_DESCRIPTOR_OFFSET_GENERATION,
  MEMORY_DESCRIPTOR_OFFSET_FLAGS,
  PACKET_DESCRIPTOR_SIZE,
  PACKET_DESCRIPTOR_OFFSET_TRACK_INDEX,
  PACKET_DESCRIPTOR_OFFSET_PAYLOAD,
  PACKET_DESCRIPTOR_OFFSET_SIDE_DATA,
  PACKET_DESCRIPTOR_OFFSET_PTS_MS,
  PACKET_DESCRIPTOR_OFFSET_DTS_MS,
  PACKET_DESCRIPTOR_OFFSET_DURATION_MS,
  PACKET_DESCRIPTOR_OFFSET_FLAGS,
  PACKET_DESCRIPTOR_OFFSET_EPOCH,
  FRAME_DESCRIPTOR_SIZE,
  FRAME_DESCRIPTOR_OFFSET_TRACK_INDEX,
  FRAME_DESCRIPTOR_OFFSET_PAYLOAD,
  FRAME_DESCRIPTOR_OFFSET_PLANES,
  FRAME_DESCRIPTOR_OFFSET_SIDE_DATA,
  FRAME_DESCRIPTOR_OFFSET_WIDTH,
  FRAME_DESCRIPTOR_OFFSET_HEIGHT,
  FRAME_DESCRIPTOR_OFFSET_PTS_MS,
  FRAME_DESCRIPTOR_OFFSET_DURATION_MS,
  FRAME_DESCRIPTOR_OFFSET_FLAGS,
  FRAME_DESCRIPTOR_OFFSET_EPOCH,
} from './abi-constants';

export {
  ABI_VERSION_MAJOR,
  ABI_VERSION_MINOR,
  ABI_VERSION,
  MEMORY_DESCRIPTOR_SIZE,
  MEMORY_DESCRIPTOR_OFFSET_REGION,
  MEMORY_DESCRIPTOR_OFFSET_OFFSET,
  MEMORY_DESCRIPTOR_OFFSET_LENGTH,
  MEMORY_DESCRIPTOR_OFFSET_CAPACITY,
  MEMORY_DESCRIPTOR_OFFSET_GENERATION,
  MEMORY_DESCRIPTOR_OFFSET_FLAGS,
  PACKET_DESCRIPTOR_SIZE,
  PACKET_DESCRIPTOR_OFFSET_TRACK_INDEX,
  PACKET_DESCRIPTOR_OFFSET_PAYLOAD,
  PACKET_DESCRIPTOR_OFFSET_SIDE_DATA,
  PACKET_DESCRIPTOR_OFFSET_PTS_MS,
  PACKET_DESCRIPTOR_OFFSET_DTS_MS,
  PACKET_DESCRIPTOR_OFFSET_DURATION_MS,
  PACKET_DESCRIPTOR_OFFSET_FLAGS,
  PACKET_DESCRIPTOR_OFFSET_EPOCH,
  FRAME_DESCRIPTOR_SIZE,
  FRAME_DESCRIPTOR_OFFSET_TRACK_INDEX,
  FRAME_DESCRIPTOR_OFFSET_PAYLOAD,
  FRAME_DESCRIPTOR_OFFSET_PLANES,
  FRAME_DESCRIPTOR_OFFSET_SIDE_DATA,
  FRAME_DESCRIPTOR_OFFSET_WIDTH,
  FRAME_DESCRIPTOR_OFFSET_HEIGHT,
  FRAME_DESCRIPTOR_OFFSET_PTS_MS,
  FRAME_DESCRIPTOR_OFFSET_DURATION_MS,
  FRAME_DESCRIPTOR_OFFSET_FLAGS,
  FRAME_DESCRIPTOR_OFFSET_EPOCH,
};

export interface MemoryDescriptor {
  readonly region: number;
  readonly offset: bigint;
  readonly length: number;
  readonly capacity: number;
  readonly generation: bigint;
  readonly flags: number;
}

export interface PacketDescriptor {
  readonly trackIndex: number;
  readonly payload: MemoryDescriptor;
  readonly sideData: MemoryDescriptor;
  readonly ptsMs: bigint;
  readonly dtsMs: bigint;
  readonly durationMs: bigint;
  readonly flags: number;
  readonly epoch: bigint;
}

export interface FrameDescriptor {
  readonly trackIndex: number;
  readonly payload: MemoryDescriptor;
  readonly planes: readonly MemoryDescriptor[];
  readonly sideData: MemoryDescriptor;
  readonly width: number;
  readonly height: number;
  readonly ptsMs: bigint;
  readonly durationMs: bigint;
  readonly flags: number;
  readonly epoch: bigint;
}

export const enum AbiFeatureFlags {
  Threads = 1 << 0,
  Simd = 1 << 1,
  SharedArrayBuffer = 1 << 2,
}
