//! Integration tests for the Annex-B demuxer.

use alloc::vec::Vec;
use cheetah_media_types::{TimeBase, TrackId};

use crate::{AnnexBConfig, AnnexBDemuxer, AnnexbEvent};

fn sps() -> Vec<u8> {
    // Valid Baseline profile SPS that cheetah-media-bitstream can parse.
    vec![
        0x67, 0x42, 0x00, 0x1e, 0xf8, 0x20, 0x10, 0xe2, 0x44, 0x89, 0x12, 0x80,
    ]
}

fn pps() -> Vec<u8> {
    vec![0x68, 0xce, 0x3c, 0x80]
}

fn idr() -> Vec<u8> {
    vec![0x65, 0x88, 0x80, 0x80, 0x80]
}

fn non_idr() -> Vec<u8> {
    vec![0x41, 0x9a, 0x24, 0x04]
}

fn h265_vps() -> Vec<u8> {
    // Minimal VPS generated by FFmpeg/libx265 for a 64x64 HEVC stream.
    vec![
        0x40, 0x01, 0x0c, 0x01, 0xff, 0xff, 0x04, 0x08, 0x00, 0x00, 0x03, 0x00, 0x9e, 0x08, 0x00,
        0x00, 0x03, 0x00, 0x00, 0x1e, 0x95, 0x94, 0x09,
    ]
}

fn h265_sps() -> Vec<u8> {
    vec![
        0x42, 0x01, 0x01, 0x04, 0x08, 0x00, 0x00, 0x03, 0x00, 0x9e, 0x08, 0x00, 0x00, 0x03, 0x00,
        0x00, 0x1e, 0x90, 0x04, 0x10, 0x20, 0xb2, 0xca, 0xca, 0x94, 0x98, 0x5e, 0x02, 0xdc, 0x08,
        0x08, 0x00, 0x10, 0x00, 0x00, 0x03, 0x00, 0x10, 0x00, 0x00, 0x03, 0x01, 0xe0, 0x80,
    ]
}

fn h265_pps() -> Vec<u8> {
    vec![0x44, 0x01, 0xc0, 0x73, 0x18, 0x30, 0x08, 0x90]
}

fn h265_idr() -> Vec<u8> {
    // NAL type 20 (IDR_N_LP); two-byte H.265 NAL header plus payload.
    vec![0x28, 0x01, 0xac, 0x21, 0x80]
}

fn h265_non_idr() -> Vec<u8> {
    // NAL type 1 (Trail_R); two-byte H.265 NAL header plus payload.
    vec![0x02, 0x01, 0xd0, 0x09, 0x78]
}

fn h265_config() -> AnnexBConfig {
    let mut cfg = AnnexBConfig::h265(TrackId::new(1).unwrap(), TimeBase::DEFAULT);
    cfg.max_buffer_bytes = 4096;
    cfg.max_nal_size_bytes = 4096;
    cfg
}

fn make_annexb(nals: &[Vec<u8>]) -> Vec<u8> {
    let mut out = Vec::new();
    for (i, nal) in nals.iter().enumerate() {
        if i % 2 == 0 {
            out.extend_from_slice(&[0x00, 0x00, 0x00, 0x01]);
        } else {
            out.extend_from_slice(&[0x00, 0x00, 0x01]);
        }
        out.extend_from_slice(nal);
    }
    out
}

fn default_config() -> AnnexBConfig {
    let mut cfg = AnnexBConfig::h264(TrackId::new(1).unwrap(), TimeBase::DEFAULT);
    cfg.max_buffer_bytes = 4096;
    cfg.max_nal_size_bytes = 4096;
    cfg
}

fn collect_events(demuxer: &mut AnnexBDemuxer) -> Vec<AnnexbEvent> {
    let mut events = Vec::new();
    while let Some(event) = demuxer.next_event().unwrap() {
        events.push(event);
    }
    events
}

mod h264;
mod h265;
